"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.isAdmin = exports.isStaff = exports.isApplicant = void 0;
const client_1 = require("@prisma/client");
const isApplicant = (role) => role === client_1.Role.APPLICANT;
exports.isApplicant = isApplicant;
const isStaff = (role) => role === client_1.Role.STAFF;
exports.isStaff = isStaff;
const isAdmin = (role) => role === client_1.Role.ADMIN;
exports.isAdmin = isAdmin;
