"use strict";
"use client";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.MapPopup = MapPopup;
const jsx_runtime_1 = require("react/jsx-runtime");
const link_1 = __importDefault(require("next/link"));
const lucide_react_1 = require("lucide-react");
function MapPopup({ property }) {
    return ((0, jsx_runtime_1.jsxs)("div", { className: "w-72 rounded-3xl border border-slate-200 bg-white p-4 shadow-soft", children: [(0, jsx_runtime_1.jsx)("div", { className: "overflow-hidden rounded-3xl bg-slate-100", children: (0, jsx_runtime_1.jsx)("div", { className: "aspect-[4/3] bg-gradient-to-br from-brand/10 via-slate-100 to-white" }) }), (0, jsx_runtime_1.jsxs)("div", { className: "mt-4 space-y-3", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-start justify-between gap-3", children: [(0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsxs)("p", { className: "text-sm font-semibold uppercase tracking-[0.24em] text-slate-400", children: [property.city, ", ", property.state] }), (0, jsx_runtime_1.jsx)("h3", { className: "mt-2 text-lg font-semibold text-slate-950", children: property.title })] }), (0, jsx_runtime_1.jsx)("span", { className: "rounded-full bg-brand/10 px-3 py-1 text-sm font-semibold text-brand", children: property.status })] }), (0, jsx_runtime_1.jsxs)("div", { className: "grid gap-2 rounded-3xl bg-slate-50 p-3 text-sm text-slate-600", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-center gap-2", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.DollarSign, { className: "h-4 w-4 text-brand" }), (0, jsx_runtime_1.jsxs)("span", { className: "font-semibold text-slate-950", children: ["$", property.rent, "/mo"] })] }), (0, jsx_runtime_1.jsxs)("div", { className: "flex items-center gap-2", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.BedDouble, { className: "h-4 w-4 text-brand" }), (0, jsx_runtime_1.jsxs)("span", { children: [property.bedrooms, " beds \u00B7 ", property.bathrooms, " baths \u00B7 ", property.sqft, " sqft"] })] }), (0, jsx_runtime_1.jsxs)("div", { className: "flex items-center gap-2", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.MapPin, { className: "h-4 w-4 text-brand" }), (0, jsx_runtime_1.jsxs)("span", { children: [property.address, ", ", property.city] })] })] }), (0, jsx_runtime_1.jsxs)(link_1.default, { href: `/ (marketing)/properties/${property.id}`.replace("/ (marketing)", "/(marketing)"), className: "inline-flex w-full items-center justify-between rounded-3xl bg-brand px-4 py-3 text-sm font-semibold text-white transition hover:bg-brandHover", children: ["View details ", (0, jsx_runtime_1.jsx)(lucide_react_1.ArrowRight, { className: "h-4 w-4" })] })] })] }));
}
