"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PropertyCard = PropertyCard;
const jsx_runtime_1 = require("react/jsx-runtime");
const formatters_1 = require("@/lib/helpers/formatters");
const lucide_react_1 = require("lucide-react");
function PropertyCard({ property }) {
    return ((0, jsx_runtime_1.jsxs)("article", { className: "group overflow-hidden rounded-[24px] border border-border bg-white shadow-card transition hover:-translate-y-1 hover:shadow-soft", children: [(0, jsx_runtime_1.jsxs)("div", { className: "relative overflow-hidden bg-slate-100", children: [(0, jsx_runtime_1.jsx)("div", { className: "aspect-[4/3] bg-gradient-to-br from-brand/10 via-slate-100 to-white px-4 py-5", children: (0, jsx_runtime_1.jsx)("div", { className: "h-full w-full rounded-[24px] bg-slate-200" }) }), (0, jsx_runtime_1.jsx)("button", { type: "button", className: "absolute right-4 top-4 inline-flex h-11 w-11 items-center justify-center rounded-full bg-white/90 text-slate-700 shadow-soft transition group-hover:bg-brand group-hover:text-white", children: (0, jsx_runtime_1.jsx)(lucide_react_1.Heart, { className: "h-5 w-5" }) })] }), (0, jsx_runtime_1.jsxs)("div", { className: "space-y-4 p-6", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-start justify-between gap-4", children: [(0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)("h3", { className: "text-xl font-semibold text-slate-950", children: property.title }), (0, jsx_runtime_1.jsxs)("p", { className: "mt-2 text-sm text-slate-600", children: [property.city, ", ", property.state] })] }), (0, jsx_runtime_1.jsx)("span", { className: "rounded-full bg-brand/10 px-3 py-1 text-sm font-semibold text-brand", children: property.status })] }), (0, jsx_runtime_1.jsx)("p", { className: "text-sm leading-6 text-slate-600", children: property.description }), (0, jsx_runtime_1.jsxs)("div", { className: "grid gap-3 text-sm text-slate-500 sm:grid-cols-3", children: [(0, jsx_runtime_1.jsxs)("div", { children: [property.bedrooms, " beds"] }), (0, jsx_runtime_1.jsxs)("div", { children: [property.bathrooms, " baths"] }), (0, jsx_runtime_1.jsxs)("div", { children: [property.sqft, " sqft"] })] }), (0, jsx_runtime_1.jsxs)("div", { className: "flex items-center justify-between gap-4 pt-2", children: [(0, jsx_runtime_1.jsxs)("span", { className: "text-lg font-semibold text-slate-950", children: [(0, formatters_1.currency)(property.rent), "/mo"] }), (0, jsx_runtime_1.jsxs)("button", { type: "button", className: "inline-flex items-center gap-2 text-sm font-semibold text-brand transition group-hover:text-brandHover", children: ["View details ", (0, jsx_runtime_1.jsx)(lucide_react_1.ArrowRight, { className: "h-4 w-4" })] })] })] })] }));
}
